#!/usr/bin/env python3
"""
Phase 3 Production Hardening Smoke Test

Verifies:
1. Legal disclaimer is present on success
2. Refusals are explicit and structured
3. Logs are written for every request

Output:
- "PHASE 3 READY" if all checks pass
- "PHASE 3 FAIL" if any check fails
"""

import json
import requests
import sys
from pathlib import Path

BASE_URL = "http://localhost:8000"
LOG_FILE = Path("logs/production_requests.jsonl")

LEGAL_DISCLAIMER = "This response is generated by an AI system for informational purposes only and does not constitute legal advice."


def check_health() -> bool:
    """Check server is running."""
    try:
        resp = requests.get(f"{BASE_URL}/health", timeout=5)
        return resp.status_code == 200
    except Exception:
        return False


def count_log_lines() -> int:
    """Count lines in production log file."""
    if not LOG_FILE.exists():
        return 0
    with open(LOG_FILE) as f:
        return sum(1 for _ in f)


def test_success_has_disclaimer() -> bool:
    """Test 1: Success response must have legal disclaimer."""
    print("\n[TEST 1] Success response has legal disclaimer")
    
    resp = requests.post(
        f"{BASE_URL}/moe-generate",
        json={"query": "What is Section 420 IPC about cheating?"},
        timeout=120
    )
    
    if resp.status_code != 200:
        print(f"  FAIL: HTTP {resp.status_code}")
        return False
    
    data = resp.json()
    
    if data.get("status") != "success":
        # Refusal is acceptable, but we need at least one success test
        print(f"  SKIP: Got refusal instead of success (status={data.get('status')})")
        print(f"  Reason: {data.get('reason', 'unknown')}")
        return True  # Not a failure, just couldn't test
    
    if data.get("disclaimer") != LEGAL_DISCLAIMER:
        print(f"  FAIL: Missing or incorrect disclaimer")
        print(f"  Expected: {LEGAL_DISCLAIMER}")
        print(f"  Got: {data.get('disclaimer', 'MISSING')}")
        return False
    
    print(f"  PASS: Disclaimer present")
    return True


def test_refusal_is_structured() -> bool:
    """Test 2: Refusal must have status, reason, and message."""
    print("\n[TEST 2] Refusal response is structured")
    
    resp = requests.post(
        f"{BASE_URL}/moe-generate",
        json={"query": "What is the law?"},  # No section reference
        timeout=120
    )
    
    if resp.status_code != 200:
        print(f"  FAIL: HTTP {resp.status_code}")
        return False
    
    data = resp.json()
    
    if data.get("status") != "refused":
        print(f"  FAIL: Expected refusal, got status={data.get('status')}")
        return False
    
    # Check required fields
    required_fields = ["status", "reason", "message"]
    missing = [f for f in required_fields if f not in data]
    
    if missing:
        print(f"  FAIL: Missing required fields: {missing}")
        return False
    
    # Verify no disclaimer on refusal
    if "disclaimer" in data:
        print(f"  FAIL: Disclaimer should NOT be present on refusal")
        return False
    
    print(f"  PASS: Refusal is structured (reason={data['reason']})")
    return True


def test_empty_query_refused() -> bool:
    """Test 3: Empty query must be refused."""
    print("\n[TEST 3] Empty query is refused")
    
    resp = requests.post(
        f"{BASE_URL}/moe-generate",
        json={"query": ""},
        timeout=30
    )
    
    if resp.status_code != 200:
        print(f"  FAIL: HTTP {resp.status_code}")
        return False
    
    data = resp.json()
    
    if data.get("status") != "refused":
        print(f"  FAIL: Empty query should be refused")
        return False
    
    if data.get("reason") != "empty_query":
        print(f"  WARN: Expected reason='empty_query', got '{data.get('reason')}'")
    
    print(f"  PASS: Empty query refused")
    return True


def test_short_query_refused() -> bool:
    """Test 4: Short query must be refused."""
    print("\n[TEST 4] Short query is refused")
    
    resp = requests.post(
        f"{BASE_URL}/moe-generate",
        json={"query": "Help"},
        timeout=30
    )
    
    if resp.status_code != 200:
        print(f"  FAIL: HTTP {resp.status_code}")
        return False
    
    data = resp.json()
    
    if data.get("status") != "refused":
        print(f"  FAIL: Short query should be refused")
        return False
    
    print(f"  PASS: Short query refused")
    return True


def test_logs_written() -> bool:
    """Test 5: Logs must be written for every request."""
    print("\n[TEST 5] Production logs are written")
    
    initial_count = count_log_lines()
    
    # Make a request
    requests.post(
        f"{BASE_URL}/moe-generate",
        json={"query": "What is Section 302 IPC?"},
        timeout=120
    )
    
    final_count = count_log_lines()
    
    if final_count <= initial_count:
        print(f"  FAIL: No new log entries (before={initial_count}, after={final_count})")
        return False
    
    # Verify log format
    with open(LOG_FILE) as f:
        lines = f.readlines()
    
    if not lines:
        print(f"  FAIL: Log file is empty")
        return False
    
    last_entry = json.loads(lines[-1])
    required_fields = ["request_id", "timestamp", "query", "status", "latency_ms"]
    missing = [f for f in required_fields if f not in last_entry]
    
    if missing:
        print(f"  FAIL: Log entry missing fields: {missing}")
        return False
    
    print(f"  PASS: Logs written ({final_count - initial_count} new entries)")
    return True


def main():
    print("=" * 50)
    print("PHASE 3 PRODUCTION HARDENING SMOKE TEST")
    print("=" * 50)
    
    # Check server health
    if not check_health():
        print("\nFAIL: Server not running")
        print("Start with: uvicorn src.inference.server:app --port 8000")
        print("\nPHASE 3 FAIL")
        sys.exit(1)
    
    print("Server healthy")
    
    # Run tests
    results = []
    results.append(("Success has disclaimer", test_success_has_disclaimer()))
    results.append(("Refusal is structured", test_refusal_is_structured()))
    results.append(("Empty query refused", test_empty_query_refused()))
    results.append(("Short query refused", test_short_query_refused()))
    results.append(("Logs written", test_logs_written()))
    
    # Summary
    print("\n" + "=" * 50)
    print("SUMMARY")
    print("=" * 50)
    
    passed = sum(1 for _, r in results if r)
    total = len(results)
    
    for name, result in results:
        status = "PASS" if result else "FAIL"
        print(f"  {name}: {status}")
    
    print(f"\nTotal: {passed}/{total}")
    
    # Final verdict
    print("\n" + "=" * 50)
    if passed == total:
        print("PHASE 3 READY")
        print("=" * 50)
        sys.exit(0)
    else:
        print("PHASE 3 FAIL")
        print("=" * 50)
        sys.exit(1)


if __name__ == "__main__":
    main()
